# -*- coding: utf-8 -*-

from datetime import datetime, timedelta

import time

IS_TEXT = {
    1: [
        "In this section I will take a look at some of these explanations.",
        "Unsurprisingly, the liar sentence fails (at least some of) these tests.",
        "And, again, each of them is equivalent* to its own negation.",
        "If so, any choice among these candidates will be arbitrary.",
        "No state of affairs is the completion of two distinct relations.",
        "Similarly for: ‘Merrick Road runs parallel to Sunrise Highway.'",
        "But, as Soames makes clear, this is for illustrative purposes only.",
        "On some ways that ¬H would be true, there would be no stellar parallax.",
        "The idea of blinding analyses goes back several decades.",
        "Sometimes we speak of a better or worse sense of taste, or simply taste.",
        "Reduction of terms therefore appears to be the initial problem.",
        "A different sort of delineation is often required.",
        "Their identity and integrity would thus not be compromised.",
        "I will proceed as follows. In the next section, I argue for (a).",
        "Asking the question of ‘what is your method of believing that p?'"
        "is essentially asking ‘what is your way of believing that p?'",
        "Henry forms a true perceptual belief that there is a white barn.",
        "Mark believes her. As it happens, Mark's brain has a slightly odd structure.",
        "I saw that he was almost as critical of his own ideas.",
        "As I have said, this is not one of the theories about self-interest.",
        "Thus, for all except misers, being rich is not an ultimate aim.",
        "Suppose that I steal whenever I believe that I will not be caught.",
        "On our theory about self-interest, this may be better for her.",
        "Suppose next that I am transparent, unable to deceive others.",
        "According to S, our formal aim is not a substantive aim.",
        "Suppose that I cling to some rock as a mere means of escaping death.",
        "I realize that it would not be rational to give this man the gold.",
        "You are not compelled to do what you believe to be irrational.'",
        "And this would be, on the whole, worse for me. It would make my work boring.",
        "Kate may be wrong to assume Psychological Determinism.",
        "The same would be true of our beliefs about rationality.",
        "But since doing so would be clearly worse for you, this risk would be small.",
        "But, like you, I do not now believe in the pure Self-interest Theory.",
        "I have described some of the ways in which we can change our motives.",
        "Since such theories have seldom been discussed, this is easy to forget.",
        "Since I know this, C may tell me to try to be a pure do-gooder.",
        "If I am lucky, it may not be bad for me to become like this.",
        "Since Clare loves her child, she would have saved him rather than several strangers.",
        "But it is in fact impossible that our love could be like this.",
        "This is what is most plausible in the doctrine that ought implies can.",
        "We may believe that these claims do not sufficiently meet this objection.",
        "We may think the same about some of the other cases of this kind.",
        "I could refuse to act wrongly, even though this would wreck my career.",
        "These four claims assume that rationality I show that this is false.",
        "This would be why we caused ourselves to believe this morality.",
        "Because we believe this other theory, this will affect what we do.",
        "It would take at least a book to decide between these different views.",
        "Suppose that, because we all believe C, we are all pure do-gooders.",
        "Consider next a Self-interest Theorist who is a Hedonist.",
        "He also believes that suffering is bad,and ought to be relieved.",
        "On this version of C, I would not, in this case, be acting wrongly.",
        "20. CONCLUSIONS I shall now summarize the second half of this chapter.",
        "It is plausible to claim that all these theories are -50indirectly self-defeating.",
        "I shall explain in Section 26 how this objection can be partly met.",
        "When the Positive Condition holds, the outcomes are as shown below.",
        "It would be true, for instance, if the benefits were randomly spread.",
        "These Dilemmas are usually described in self-interested terms.",
        "But it might receive unanimous support in a referendum.",
        "With this task, theory helps. Prisoner's Dilemmas need to be explained.",
        "So do their moral solutions. Both have been too little understood.",
        "There are few people whose only moral motive is trustworthiness.",
        "He will prefer to join, even if doing so will be worse for him.",
        "Consider The First Rescue Mission: I know all of the following.",
        "I can therefore do more good if I go elsewhere and save fifty lives.",
        "This is what each does, not by himself, but with the help of the others.",
        "An act harms someone if its consequence is that someone is harmed more.",
        "What should we claim in cases where this is not true? Consider Case Two.",
        "It does not follow that this person has done what he ought to have done.",
        "There is only one correct description of the effect of my act.",
        "It gives to each of the thousand men an extra thousandth of a pint.",
        "What we can appeal to is a claim about what we together do.",
        "They drink slightly less water. But this effect is imperceptible.",
        "Since this conclusion is absurd, we must reject either (A) or (B).",
        "And rejecting (B) has implications like those of rejecting (A).",
        "You must then conclude that, in this case, no turning of a switch is wrong.",
        "Whether this is so depends on the answer to another question.",
        "The effect is the same as in the days when all the torturers act.",
        "On either answer, we must abandon what I call the Fifth Mistake.",
        "But the water-cart can hold only one thousand pints. It is now full.",
        "As I shall argue in the next chapter, this claim is not justified.",
        "We can have real though small effects on thousands or millions of people.",
        "But this would not be true when they would be, on the whole, worse for someone.",
        "We are causing the S-given aim of each to be better achieved.",
        "If each does what is best for himself, we do worse than we could for each.",
        "It is a theory about individual rationality.",
        "It is a theory about what we have reasons to do at each time.",
        "He must insist that reasons for acting cannot be time-relative.",
        "Consider next those benefits that I ought to try to give my child.",
        "It treats parental care as a mere means. We may think it more than that.",
        "This is an aim that the other can directly cause to be achieved.",
        "But in most cases we ought to be disposed to act upon these claims.",
        "As I have argued, this might be no objection to our theory.",
        "Can it be claimed that this is no objection? This seems very doubtful.",
        "Only by failing to give priority to our own children.",
        "If we follow M, we are not doing what we believe to be wrong.",
        "I would thereby cause M-given aims to be, on the whole, worse achieved.",
        "It may be true that what matters most is that we avoid wrongdoing.",
        "Can we claim that the avoidance of wrong-doing is all that matters?",
        "Could this provide a defence? This is the central question I have raised.",
        "Each should do only what he can rationally will that we all do.",
        "It would be worse for nearly everyone if no one helped such strangers.",
        "It does not refute S, but it does refute part of their own theory.",
        "C may appeal to several principles about what makes outcomes bad.",
        "If someone acts in a certain way, we may know what his reason was.",
        "But this desire indirectly provides a reason for acting.",
        "5 This desire is not irrational. It is an excellent whim.",
        "Preferring the worse of two pains, for no reason, is irrational.",
        "One is extremely common: caring more about the nearer future.",
        "This is why he called Egoism one of the \"Methods of Ethics\".",
        "Similar remarks apply to Moslems, many Buddhists, and Hindus.",
        "I shall therefore call this desire the bias in one's own favour.",
        "There are different versions of the Critical Present-aim Theory.",
        "It is rational for me to do what I know will be worse for me.",
        "According to S, reasons for acting can be agent-relative.",
        "You do not have a reason to do whatever will be best for me.",
        "He need not add 'here' because, since I am here, I cannot be elsewhere.",
        "We can call such claims incompatible with full relativity.",
        "But, if we accept the first claim, we should also accept the second.",
        "Following Nagel, I distinguished two kinds of reason for acting.",
        "130 Suppose next that, as Nagel now believes, reasons can be relative.",
        "My children could not possibly both exist and not be my children.",
        "As I have said, a Present-aim Theorist can also make this claim.",
        "Both theories appeal to a person's desires about his own life.",
        "One of my strongest desires is that Venice never be destroyed.",
        "And you must have changed your mind when you ceased to want Venice to be saved.",
        "There is a vast range of possible and worthy objects of concern.",
        "And this desire was not conditional on its own persistence.",
        "But that a pain is someone else's does make it less painful to you.",
        "He might say that, when we compare the questions 'To whom does it happen?'",
        "While she is away, it is clear to me which I prefer to be true.",
        "During my painful operation I shall have all my memories.",
        "(3) It has not been shown that the bias towards the near is bad for us.",
        "We can express such desires with other parts of our language.",
        "It may be thought that we actually have such backward-looking states.",
        "And you will be dead tomorrow. So you ought to be greatly troubled.'",
        "On the day after, Timeless is just as glum. 'Why should I be relieved?",
        "The S-Theorist might now support this claim in a different way.",
        "This excitement would be claimed by many not to be irrational.",
        "'Now' moves into the the future. This is why past pains do not matter.",
        "I call these the Past or Future Suffering of Those We Love. Case One.",
        "My mother did have many months of suffering, but she is now dead.",
        "What distresses me is not just to learn of my mother's painful death.",
        "I admit that, when I learn this fact, I might be somewhat less distressed.",
        "The S-Theorist might say: 'In one sense, this is not irrational.",
        "But, in another sense, you should not be biased towards the present.",
        "Since that is so, you ought now to regret even your present bias.",
        "But, given what I then most wanted, this act was not irrational.",
        "He is doing what, impartially considered, has the best effects.",
        "As these cases show, S insists on a biased pattern of concern.",
        "He is doing what, impartially considered, has the best effects.",
        "As these cases show, S insists on a biased pattern of concern.",
        "How can so many people have been mistaken? There are two answers.",
        "But this time, when I press the green button, I do not lose consciousness.",
        "'Wait a minute', I reply, 'If I'm here I can't also be on Mars'.",
        "But it seems to be damaging the cardiac systems which it scans.",
        "Some believe that we can learn little. This would have been Wittgenstein's view.",
        "And these are beliefs, not about our words, but about ourselves.",
        "This second view seems to be supported by the end of my story.",
        "I shall remain on the Branch-Line, on Earth, which ends a few days later.",
        "Since I can talk to my Replica, it seems clear that he is not me.",
        "This is the simplest version of this view. There is a better version.",
        "Some claim (7) A nation just is these citizens and this territory.",
        "A similar claim applies when some fact can be described in two ways.",
        "I shall then argue for conclusion (1), that we are not such entities.",
        "Butler's objection may be interpreted in a different way.",
        "Strawson discusses an argument for this view, suggested by Kant.",
        "This would not be clear if all these thoughts began with the phrase 'It is thought:.",
        "This becomes true of most of the people in the world's population.",
        "This is not the claim that Derek Parfit might have been Napoleon.",
        "The surgeon tells me that, while I am in pain, he will do several things.",
        "We are led there, by what seem innocent steps, to absurd conclusions.",
        "And I could know which particular connections would or would not hold.",
        "But, in these cases, these are not two different possibilities.",
        "They are merely two descriptions of the very same course of events.",
        "When Williams gives his version of this argument, he rejects this view.",
        "We could believe that there is a sharp borderline between two cases.",
        "In the first case in this spectrum, at the near end, nothing would be done.",
        "This is another view that I believe to be indefensible.",
        "This Spectrum shows, I believe, that certain views must be held together.",
        "On this view, nations cannot be referred to, since they do not exist.",
        "With one of his hands the person writes 'Red', with the other he writes 'Blue'.",
        "Rather, I have two minds. This objection does not raise a real question.",
        "Here too, I believe that this objection does not raise a real question.",
        "In this case there are two streams of consciousness for only ten minutes.",
        "This claim conflates these two sets. A Reductionist may now intervene.",
        "Persons need not be claimed to be the thinkers of any of these thoughts.",
        "Our belief is about what is involved in the lives of persons.",
        "The claim may be that, before My Division, they together were me.",
        "This is even less plausible than the claim I have just rejected.",
        "If what happens to me does not happen to X, X cannot be me.",
        "All such connections hold between me and each of the future people.",
        "Nothing is missing. What is wrong can only be the duplication.",
        "In the case of My Division these relations do not coincide.",
        "This would be what each of the resulting people would most want to do.",
        "It can wait in the wings, to reappear when the action demands it.",
        "I cannot be one and the same person as two different people.",
        "This criterion implies that my Replica on Mars will be me.",
        "As Williams admits, a similar argument can challenge this view.",
        "The second involves the continuity of just a few more cells.",
        "As a precaution, before each walk, I could have a new blueprint stored.",
        "The best description is that I shall be neither resulting person.",
        "I have now reviewed the main arguments for the Reductionist View.",
        "This belief is not true. Is the truth depressing? Some may find it so.",
        "But we must decide what matters before choosing our description.",
        "These claims about this similarity I shall in future omit.",
        "It is a case where there is a best answer to an empty question.",
        "I know the full facts even if we have not yet made this decision.",
        "My attitude should depend on the importance of facts (b) and (c).",
        "Why should I want it to be true that this brain and body gets to Mars?",
        "In the rest of my life, it would be enough to form this intention.",
        "I might in one stream write a letter to myself in my other stream.",
        "I believe both that I would and that I ought to love her Replica.",
        "This reaction is unjustified, since there is no such further fact.",
        "59 Suppose that I was physically obsessed with Mary Smith's body.",
        "I claim that, in such a world, ordinary love would survive unchanged.",
        "But love would still be love of a particular individual.",
        "Since Padua is close to Venice, both can be easily fulfilled.",
        "Suppose next that I love Wagner, and always vote for a Socialist.",
        "As I have argued, there is no fact involved which is all-or-nothing.",
        "Each branch corresponds to what is thought of as the life of one person.",
        "I shall assume that neither relation matters more than the other.",
        "This is another way in which I would regret such a reduction.",
        "(They can share a past self without being the same self as each other.)",
        "A is the person whose life is represented by the three-lined branch.",
        "I shall now turn from imaginary cases to actual lives.",
        "Because this is true, I could 276 rationally hope that Lefty soon dies.",
        "Suppose next that a Non-Reductionist ceases to believe his view.",
        "By appealing to the Reductionist View, we can challenge these claims.",
        "Since Darwin, it gives new significance to the Great Chain of Being.",
        "I know 283 that I am doing what is likely to be much worse for me.",
        "According to some of these, loss of memory would be important.",
        "This is what my claim implies. In this section I have described three views.",
        "That it is unjust to punish the innocent cannot be denied.",
        "If we accept the Reductionist View, we may decide otherwise.",
        "What is wrong with this claim? Why should the effect be only on the scope?",
        "For those who accept the Extreme Claims, the effect may be disturbing.",
        "', this would here be an empty question. These last claims are controversial.",
        "This claim applies to everyone. You were conceived at a certain time.",
        "As this case suggests, the Social Discount Rate is indefensible.",
        "9 It may be said: In one sense, this girl's decision was worse for her child.",
        "In the case of The 14-Year-Old Girl, we are not forced to appeal to Q.",
        "The effects of the different policies would be as shown below.",
        "Either programme would halve the incidence; the rate would drop to 1,000 a year.",
        "Though they do not know this fact, the people in one group could have been cured.",
        "In considering both cases, I accept the No-Difference View.",
        "This cannot be claimed about our choice of the Risky Policy.",
        "They would therefore not regret our choice of the Risky Policy.",
        "The objection to our choice cannot be that it harms these people.",
        "This person asks us to shoot him, so that he does not die painfully.",
        "Suppose we believe that each person has a right to live a full life.",
        "The appeal to this effect is not an appeal to anyone's rights.",
        "Would it be better if an extra life is lived that is worth living?",
        "Fortunately, this is only one of several possible cases.",
        "We can ask the same questions; but we must use an unfamiliar phrase.",
        "Such a method of moral reasoning cannot be acceptable.",
        "This benefit is greater if this person's life is more worth living.",
        "It would be better if, during this period, no one existed.",
        "This is no answer. Consider two possible future histories.",
        "We can make this view more plausible if we add the following claims.",
        "On your new theory, the lives lived in these outcomes would have no value.",
        "We can assume that, in A, every life is above this level.",
        "On our view, if B was large enough, it would be better than A.",
        "These people have lives that are worth living, and they affect no one else.",
        "There is another way in which A+ might be claimed to be worse than A.",
        "In this version of this case, this conclusion is even more absurd.",
        "The person I call Rich is better off than the person I call Poor.",
        "The Mere Addition Paradox does not force us to this conclusion.",
        "This is why A+ is worse than A.' The argument can be restated.",
        "Somewhere between these two we must change our view. Where should the change come?",
        "There is no longer inequality between the two best-off groups.",
        "The other group have a quality of life that is even higher.",
        "If we accept this view, we must apply it to the actual world.",
        "But it is also hard to believe that New Z is better than A+.",
        "We cannot solve this problem unless we attack it in its own terms.",
        "I believe that, in principle, (4) is another welcome conclusion.",
        "I believe that the difference between (2) and (3) is very much greater.",
        "Since it would be worse for them if they threaten me, they will not 397 do so.",
        "Many assume that it would be more damaging to morality.",
        "Hume here implies that, if we were forced to choose, we would choose selfinterest.",
        "And suppose that I believe that, when S and P conflict, neither wins.",
        "At the point that we have now reached, we no longer have alternatives.",
        "We cannot make a further change in our view about self-interest.",
        "These will be cases where my desires are not about my own life.",
        "Though my brain has been tampered with, it is clearly the very same brain.",
        "Nagel makes two claims about what he and others mean by the word 'I'.",
        "On this view, Case One gives me life, and Case Two death. Is this plausible?",
        "In Case Two, he does all the removing before all the inserting.",
        "It may be objected: 'In some cases, this is not a moral question.",
        "We ought to discount those predictions that are more likely to be false.",
        "Predictions about the further future are more likely to be false.",
        "These are the people to whom we stand in certain special relations.",
        "Our grandchildren cannot all be born before all our children.",
        "Judgements of this kind are often made about the last part of some life.",
        "He might thus conclude that these parts of his life were better than nothing.",
        "This person would not have been worse off if he had never existed.'",
        "In contrast, there are no particular people who never exist.",
        "If we had not caused him to exist, this would not have been worse for him.'",
        "Suppose India in 1800 could have had any of three constitutions.",
        "One of my strongest desires was to be a successful parent.",
        "The agency by which memory is produced we have just explained.",
        "We should first note the sense of 'can' in the doctrine that ought implies can.",
        "If (b) happens, it will be better for each that he made his promise.",
        "But if (c) happens, it will be worse for each that he made his promise.",
        "But in cases that involve large numbers, there is another problem.",
        "Are we causing the S-given aims of each to be better achieved?",
        "I would need to ask, 'What am I to do now in this half of my mind?",
        "Though they have some force, the two objections should not be overstated.",
        "For an argument supporting the view that I accept, see RUSSELL.",
        "Scanlon sketches a plausible moral theory built upon this claim.",
        "It may therefore stand. Similar remarks apply to every Row.",
        "(See GRIFFIN (4).) There is a better way to explain the Asymmetry.",
        "It is true that, if my couple have this child, this would be good for him.",
        "With this entailment broken, the Wide and Narrow Principles diverge.",
        "One of two outcomes may be worse though it has more personal value.",
        "This will be clear if we remember two of my other conclusions.",
	"Be my guest—posit a primitive property of sets if you want.",
	"But the argument I want to glean from him rests on three premises:",
	"Suppose one draws the first circle in ink and the other in crayon.",
	"The second problem is that this does not explain what the realist needs.",
	"What is it about pain in virtue of which it ought be minimized?",
	"To the contrary, there is the notion of an a priori truth.",
	"If one had done so, one would have made, of course, a different object.",
	"It does not feel cold and it probably would if it were made of ice.",
	"Is it the case that if someone knows something, she knows that she knows it?",
        "I thank Richard Vernon and Charles Jones for their support and feedback.",
	"To say that he does not exist is to say that this is not the case.",
	"Recall that when this talk was given, the lectures were fairly recent.",
	"Hamlet thought many things, but does it follow that Hamlet existed?",
	"In that case, I think the intent of the play is that the ghost was real.",
	"Clearly, nothing is intrinsically wrong with (1), nor is it ill-formed.",
	"We then attribute truth values to these, using a predicate ‘true1'.",
	"The notion of an acceptable structure is developed in chap.",
	"Yet (12) is ungrounded (has no truth value in the minimal fixed point).",
	"The man to whom the speaker refers is—let us suppose—kind to her.",
	"Grice's theory has become very complex and I am not quite sure.)",
	"Moore's “paradox of analysis” may be a related problem.",
	"According to Mill, a proper name is, so to speak, simply a name.",
	"Not that the puzzle extends to all translations from English to French.",
	"Probably this is why Nozick did not notice the redundancies.",
	"The material of which they are made is not really the main point.",
	"The owner may not so much as have heard of the papier-mâché barns.",
	"Granting the latter principle, the following steps preserve knowledge.",
	"When the specialized philosophical journal began, I don't know.",
	"For the general case, see the appropriate discussion below.)",
	"Why it took Quine a long time to realize this is a little obscure.)",
	"It is presupposed here, and its actual truth is irrelevant.",
	"I will skip for the moment the next two puzzles, which are simpler.",
	"And his relations with a later wife were much less admirable.",
	"That's impossible, and that's what the owner is complaining about.",
	"That implies that there was a unique size that the guest thought the yacht was.",
	"I believe my own example is correct. That is an advantage.",
	"The Sheffer stroke was, in fact, already known to Peirce, but forgotten.",
	"Later, Salmon wrote he doubted they were trying to avoid hydras.",
	"Though Goldfarb has lost this battle, in a way his basic point is right.",
	"Like many other of my works, publication has been long delayed.",
	"I also heard it directly from him; I don't remember the date.",
	"However, in the present case, the order is in a way reversed.",
	"There was no concern with the unique set (or class) of possible worlds.",
	"Any number of points and examples trace back in some way to Kit.",
	"The idea is elusive, but we rely on it all the time.",
	"Content-inclusion is elusive, I said, but this might be questioned.",
	"This is trivial unless the properties are somehow restricted.",
	"Consider Albert, prince consort. He lived in the nineteenth century.",
	"Well, w has a certain number of stars, let's say a billion.",
	"How are we to get an intuitive handle on the function m(.",
	"Let's return now to a question left hanging at the end of section 2.1.",
	"How can it be, when there is no Pegasus for it to be true of?",
	"What A says about m has the advantage of always existing.",
	"¬A conveys that it too is permitted by the world's m-condition.",
	"This is enough, it seems, to change the state of things where s is concerned.",
	"Mount Everest has never been climbed is false in the actual world @.",
	"It appears that s = how S is true is only half of the story.",
        "David hacks into Brenda's computer to steal photographs of her.",
	"We know what it takes for one subject matter to include another.",
	"What should we expect to percolate up in the case of content-parts?",
	"Are the truthmaking relations similarly indiscriminate?",
	"The two together, then, are raveblack because a, b, c,. . . are black.",
	"The point for now is that we need sometimes to have a foot in both camps.",
	"Whether reversing conjuncts can affect sense for Frege, I don't know.)",
	"I wish I had more to say about how the two models interact.",
	"Sobel starts with the images of worlds, which he calls world-tendencies.",
	"It is relevant to features of the outcome that he cares about.",
	"It specifies the extent of my influence, namely full control.",
	"One can, after all, express contrition without apologizing.",
	"To hold such a view is to commit a sort of mental suicide.",
	"Sometimes this sentence token expresses a truth, sometimes a falsehood.",
	"Steven judges out loud that the tree is at most twenty-five feet high.",
	"They know her to be a trustworthy informant. They reason as in #1.",
	"They reason as in ###1. The twelve arguments differ in two dimensions.",
	"In the good case, one believes truly that one is not in the bad case.",
	"In the bad case, one believes falsely that one is not in the bad case.",
	"Yet, when I see a dachshund, I still know that I am seeing a dog.",
	"The bad case in a sceptical argument may be a case in point.",
	"We can follow the rule 'Proportion your voice to the size of the room'.",
	"The kind of thing which hypotheses explain is propositional.",
        "And could the sense of smell allow the perception of discrete objects?",
        "Rather, students and teachers come together for the sake of knowledge.",
        "He distinguishes seven philosophical relations",
        "Now the question is: where does the idea of a unit come from?",
	"My belief is in fact true. But I do not know that draw n+1 was red.",
	"Witness A says 'I saw the first six tosses; it landed heads each time'.",
	"It is enough that we often know whether the condition obtains.",
	"The aim of the next section is to understand that phenomenon.",
        "So B and C must agree everywhere, and so are identical.",
        "Nonetheless, we might wonder if this conflict is only apparent.",
	"Given a speech act A, one end p.239 can ask 'What are the rules of A?'.",
	"An attractively simple suggestion is this. There is just one rule.",
	"Consideration of lotteries suggests a negative answer.",
        "We need studies in which infants' abilities to act are impaired.",
	"That assumption needs testing; it is rejected in the next section.",
	"If so, 'assert' will express correspondingly different contents.",
	"In some sports, it is said that some rules are being breached most of the time.",
	"Neither belief nor belief on good evidence warrants assertion.",
        "So this issue does not seem to be unique to collective functions.",
	"The limits discussed in this chapter are far more prosaic than those.",
        "Then a nickel is tossed. If the nickel comes up heads, you win 2n dollars.",
	"In what sense could that be known at level i+1 but not at level i?",
	"Knowledge of it in w is knowledge of nothing interesting.",
        "Suppose I throw a cat at a window, causing the window to break.",
        "Let me clarify the technical notion of a pure reflex",
        "So this issue does not seem to be unique to collective functions.",
	"We can understand 'unknown' broadly enough to exclude such cases.",
	"Cosmic history follows vastly divergent paths in s and s*.",
        "The term “Inference to the Best Explanation” was coined by Harman.",
        "Diana takes an archery shot and hits the selected target.",
        "A typical car has an engine, a chassis, wheels, doors, and so on.",
        "Science is our best example of such a social achievement.",
        "The size of the whole is the sum of the sizes of its disjoint parts.",
        "Addressing Brewer's current position would take us too far afield.",
        "One example of a signaling system is human languages.",
        "Move a part of the account a bit, and the whole edifice crumbles.",
        "This paper rejects both accounts and provides a new alternative.",
        "Some researchers respond in the affirmative.",
        "For reasons of space, I leave this issue open for further studies.",
        "Rather, Leibniz holds that matter must deform and recoil in impact.",
        "So let's ask Mary: Mary, what do you think of licorice? Tasty?",
        "Rather, a person at different ages knows the world differently.",
        "that casts serious doubt over the existence of the radical.",
        "Second, the context of imagination is tied to the speaker.",
        "On the one hand, Hanks accepts as a matter of course the Frege Point.",
        "For, remember the tale of Basic Law V and Russell's paradox.",
        "First, power is a function of the number of goods an agent has.",
        "While driving, I see a car pull out into my lane: I hit the brakes.",
        "Suppose someone cuts in line in front of you at the supermarket.",
        "What should knowledge first theorists say about the value of knowledge?",
        "We could observe a means and write down a list of candidate outcomes.",
        "This is all well and good, and does make sense of some of their behavior.",
        "Like propositions, questions and directives should be cognitive acts.",
        "Considered purely as a philosopher, Marx has grave shortcomings.",
        "Kant's early works are more concerned with science than with philosophy.",
        "At a certain stage of human development it is natural.",
        "Locke's father was a Puritan, who fought on the side of Parliament.",
        "Suppose your daughter has been raped and then killed by enemy soldiers.",
        "This understanding of everything as part of God is love of God.",
        "The terms in science are of first intention; in logic, of second.",
        "The brief career of Alexander suddenly transformed the Greek world.",
        "Quine's view is what I call a theory-commitments view of existence.",
        "Susan disagrees with the theory presented at the conference.",
        "Dispositions drive the ever-changing display of the imagery.",
        "Rene and Cathy go to Fancy Foods at noon every Friday.",
        "Carl, hating David and wanting him dead, pushes David in the lake.",
        "Our bodies move regularly, our eyes nearly constantly.",
        "Disjunctive views do not respect the unity of identity.",
        "She is presently pacing up and down in the garden, deep in thought.",
        "Breaking camp on a windy day, Hiker leaves a campfire burning.",
        "I don't ever want to make even a single mistake in grading.",
        "Mary: There's a small Chinese supermarket just around the corner.",
    ],
    0: [
        "Morgan, Jerry L. (1978). Two types of convention in indirect speech acts.",
        "Politeness and face in Chinese culture. Frankfurt am Main: Peter Lang.",
        "[1903]: The Principles of Mathematics, W. W. Norton.",
        "Hardcastle, V. G., & Stewart, C. M. (2002). What do brain data really show?",
        "First, M. B., Spitzer, R. L., Gibbon, M., & Williams, J. B. W. (1997).",
        "Thought experiments: The state of the art. In M. T. Stuart, et al.",
        "Wittgenstein, L. (1969). On Certainty, translated by G.E.M. Anscombe.",
        "An introduction to non-classical logic: From if to is (2nd ed.).",
        "Making the Social World: The Structure of Human Civilization.",
        "See Lister, Public Reason and Political Community, p. 129.",
        "acdonald, R. R. (1997). On statistical testing in psychology.",
        "Fagin, R., & Halpern, J. Y. (1991). A new approach to updating beliefs. ",
        "Informal logic: A handbook for critical argumentation.",
        "Tomasello, M. (2014). A natural history of human thinking.",
        "We define ϕ → ψ as ¬(ϕ ∧ ¬ψ), so that S(ϕ → ψ) = S(ϕ) + S(ψ) + 3.",
        "Hartwell, L. H., Hood, L., Goldberg, M. L., Silver, L. M., & Veres, R. C. (2000).",
        "Bush, F. M., Francis, M., Harkins, S. W., Long, S., & Price, D. D. (1994).",
        "Kemeny, J. G., & Oppenheim, P. (1952). Degree of factual support.",
        "Pinker, S. (2003). Language as an adaptation to the cognitive niche.",
        "What does it mean to be an empiricist?. Cham: Springer. Smith, G. E. (2001).",
        "The Unity of Agency: A Kantian Response to Parfit.",
        "Craver, C. F. (2016). The explanatory power of network models.",
        "Pritchard, D., Turri, G., & Adam Carter, J. (2018). The value of knowledge.",
        "Kant, I. (2000). Critique of pure Reason (P. Guyer & A. W. Wood Trans.).",
        "ELLIOT: R., \"How to Travel Faster Than Light? \", Analysis 41, Jan. 1981.",
        "FINDLAY: J., Values and Intentions, London, George Allen and Unwin, 1961.",
        "-534141, 1982. GRIFFIN (3): J. P., \"A Substantive Theory of Rights\", unpublished paper.",
        "MCMAHAN (1): J. A., \"Problems of Population Theory\", Ethics 92, No.",
        "QUINE (2): W. V., \"What Price Bivalence?\", The Journal of Philosophy, 1981.",
        "1, Mar. 1976. SMART (2): J. J. C., ed., Problems of Space and Time, New York, Macmillan, 1976.",
	"“How to Speak of the Colors.” Philosophical Studies 68: 221– 63. Kraut, Robert.",
	"Cambridge, MA: Harvard University Press. Quine, W. V. O.",
	"2000. Philosophy and Social Hope. New York: Penguin. Rosen, Gideon.",
        "6–27. Reprinted in this volume as Chapter 5. ——— (1980). Naming and Necessity.",
        "University of California, Berkeley and Los Angeles, 1967.",
	"——— (1993) The Problem of the Essential Indexical and Other Essays.",
        "Reprinted in this volume as Chapter 6. ———. (1980). Naming and Necessity.",
	"Reprinted in this volume as Chapter 11. The First Person 321 Lewis, D. (1970).",
	"The Problem of the Essential Indexical and Other Essays.",
        "The Intentional Stance. Cambridge, MA: MIT Press. Donnellan, K. (1966).",
	"Reprinted in this volume as Chapter 5. ———. (1980). Naming and Necessity.",
	"———. (2005). “Russell's Notion of Scope.” Mind 114:1005–37. Reprinted in this volume as Chapter 8.",
        "Reprinted in this volume as Chapter 4. ———. (2005). “Russell's Notion of Scope.” Mind 114:1005–37.",
        "Enfield, N. J. (2017). How we talk: The inner workings of conversation.",
        "Philosophical Studies, 13(1):9–24, 1962. Armstrong, David M. Truth and Truthmakers.",
        "Proceeding of the Royal Society of Edinburgh, V, 43, 321–341.",
        "The British Journal for the Philosophy of Science, 58(2), 207–233. Weisberg, M. (2013).",
        "Chang, R. (2013). Commitments, reasons, and the will. In R. Shafer-Landau (Ed.",
        "Rationality through reasoning. Chichester: Wiley. Chrisman, M. (2008).",
        "Kim, J. (2002). The layered model: Metaphysical considerations.",
        "The British Journal for the Philosophy of Science (forthcoming).",
        "Calvert, J., & Martin, B. R. (2001). Changing conceptions of basic research",
	"Psychology from an Empirical Standpoint. Psychology Press, 1995.",
        "An introduction to the sociology of health and illness.",
        "f φ (AE X 1 ∨ · · · ∨ AE X N ) = x · f φ (E X 1 ∨ · · · ∨ E X N ) N N ^D ^D ^D ^D ?",
	"———. Philosophy of Logic. Harper and Row, 1971. ———. The Meaning of “Meaning”.",
        "Brewer, T. M. (2003). Two kinds of commitments (and two kinds of social groups).",
        "Baxter, D. L. M. (1988). Identity in the loose and popular sense.",
        "The division of cognitive labor. Journal of Philosophy, 87, 5–22.",
        "In A. Abraham, (Ed. ), The Cambridge handbook of imagination.",
        "The Bulletin of Symbolic Logic, 9(3), 273–298. Lewis, D. (1991). Parts of classes.",
        "The Bulletin of Symbolic Logic,",
        "doi:10.1111/j.1746-8361. 2012.01294.x. Gilmore, C. (2014). Parts of propositions. In S. Kleinschmidt (Ed.",
        "Horrigan, S. K., Courville, P., Sampey, D., Zhou, F., Cai, S., et al.",
        "Philosophical Transactions of the Royal Society B, 366, 3142–3152.",
        "East Sussex: Taylor & Francis. Fales, E. (1990). Causation and universals.",
        "Small, W. 2017. Ryle on the explanatory role of knowledge how.",
        "Time and physical geometry. The Journal of Philosophy, 64, 240–247.",
        "On the “meaning” of scientific terms. Journal of Philosophy, 62(10), 266–274.",
        "Mind, 80, 432–436. Fodor, J. A. (1975). The Language of Thought. New York: Crowell. Fodor, J.",
        "Thompson, E. (2007). Mind in life. Cambridge, MA: MIT Press. Tolman, E. C. (1932).",
        "(2005). “A Hybrid Theory of Claim-Rights.” Oxford Journal of Legal Studies 25: 257–274.",
        "Philosophical Review 64: 3–32. Raz, J. 1999. Agency, reason, and the good.",
        "Analysis 43 (January 1983): 12-14. Salmon, N. Review of Linsky, 1977.",
        "C. Lewy. New York: Macmillan, 1962. Moore, G. E. \"Facts and Propositions.\"",
        "Philosophical Papers, London: George Allen & Unwin Ltd. 1962.",
	"Dewey, J. 1938. Logic: The Theory of Inquiry. New York: Henry Holt.",
	"Philosophical Review, 74: 88-95. —— 1968. 'Knowledge, inference and explanation.'",
	"McDowell, J. H. 1977. 'On the sense and reference of a proper name.'",
	"), Philosophical Subjects: Essays Presented to P. F. Strawson.",
	"'The reality of appearances'. In R. M. Sainsbury (ed.",
        "Cambridge: MIT Press. Mellor, D. H. (1980). Things and causes in spacetime.",
	"Modeling Bounded Rationality. Cambridge, Mass. : MIT Press.",
        "Quine, W. V. & Harvard University, Grants (1931–1988). Correspondence.",
        "Philosophical Papers, 42(1), 25–48. Egger, J. B. (1978). The Austrian method.",
        "Philosophical Transactions of the Royal Society B, 369(1644), 20130490.",
	"Our Knowledge of the External World. London: Routledge. First published 1914.",
	"Notre Dame Journal of Formal Logic, 33: 89-100. end p.330 —— 1992b. 'Inexact knowledge.'",
        "Agency and the ethics of belief . London: Routledge. McHugh, C. (2012).",
        "The Proceedings of the Twentieth World Congress of Philosophy, 5, 173–179.",
        "Philosophical Studies, 173, 461–477. Krauss, S. (2017). Lying, risk, and accuracy.",
        "Causation: One word, many things. Philosophy of Science, 71(5), 805–819. Cat, J.",
        "(2015) The activity view of inner speech, Frontiers in Psychology.",
        "Boston studies in philosophy of science. Springer (forthcoming).",
        "The evolution of morality. Cambridge, MA: MIT Press.",
        "The British Journal for the Philosophy of Science, 64, 747–761. van Riel, R. (2014).",
        "Then still P = R, and by (2b), Q ≤ S, as well as by (4b) S ≤ Q, so S = Q.",
        "Hornsby, J. (1999). The facts in question: A response to Dodd and to Candlish.",
        "Time and physical geometry. The Journal of Philosophy, 64, 240–247.",
        "On the “meaning” of scientific terms. Journal of Philosophy, 62(10), 266–274.",
        "2009 2008 2007 2013b 2014c 2015a 2017 2018c 2007",
        "Philosophical Studies, 166(2), 285– 303. Reichenbach, H. (1956). The direction of time.",
        "Midwest Studies in Philosophy, 18(1), 90–120. Atkin, A. (2016). Peirce. London: Routledge.",
        "Transactions of the Charles S. Peirce Society, 35(2), 374–397. Delaney, C. F. (1982).",
        "New York: Springer. Hanks, P. (2011). Structured propositions as types. Mind, 120(477), 11–52. Hanks, P. (2015).",
        "Philosophical Studies, 172, 375–97. Fallis, D. (2015b). What is disinformation?",
        "Inference to the best explanation. London: Routledge. Lipton, P. (2004).",
        "Writings of Charles S. Peirce: A chronological edition, volume 8: 1890–1892.",
        "Introduction to logical theory. New York: Wiley. Turner, J.",
        "Gillespie, J. H. (2004). Population genetics: A concise guide (2nd ed.).",
        "Beyond the causal theory? Fifty years after Martin and Deutscher.",
        "In A. Abraham, (Ed. ), The Cambridge handbook of imagination.",
        "Analysis, 72(3), 513–517. Crisp, T. M., & Warfield, T. A. (2001). Kim's master argument.",
        "Philosophical Psychology, 15(4), 551–562. Wilson, R. S., & Franklin, C. E. (2002).",
        "Dougherty, T. and J. Walls. 2018. Two Dozen (or so) Arguments for God.",
        "Philadelphia, PA: University of Pennsylvania Press.",
        "Clark, A. (1998). Being there: Putting brain, body, and world together again.",
        "Putnam, H. (1983). Why there isn't a ready-made world. In H. Putnam (Ed.",
        "References Brooks, R. (1991). Intelligence without representation.",
        "(2009). What to do when you don't know what to do. In R. Shafer-Landau (Ed.",
        "Princeton: Martino Fine Books. Nelson, A. (1992). Reply by Alan Nelson.",
        "True to life: Why truth matters. Cambridge: MIT Press. Mill, John Stuart.",
        "Human inference: Strategies and shortcomings in social judgment.",
        "London: Routledge. Quine, W. V. (1957). The scope and language of science.",
        "Howson, C., & Urbach, P. (1991). Bayesian reasoning in science. Nature, 350(6317), 371–374.",
        "Boston, MA: Houghton, Mifflin. Goldman, A. (1979). What is justified belief?",
        "Knowledge and the flow of information. Cambridge, MA: MIT Press.",
        "Ethical Theory and Moral Practice, 4(2), 171–189. Lewis, J. D., & Weigert, A."
        "Fleck, L. (1979). Genesis and development of a scientific fact.",
        "Mares, E., & Paoli, F. (2014). Logical consequence and the paradoxes.",
        "Dixon, K. (1986). Freedom and equality. London: Routledge. Feinberg, J.",
        "New York: Farrar, Straus and Giroux. Hansson, S. O. (2016). Decision theory.",
        "Lackey, J. (2008). Learning from words: Testimony as a source of knowledge.",
        "The division of cognitive labor. Journal of Philosophy, 87, 5–22.",
        "Dever, J. (2001). Complex demonstratives. Linguistics and Philosophy, 24(3), 271–330.",
        "The British Journal for the Philosophy of Science, 66(2), 375–411. Sloan, P. R. (1992).",
        "Introduction: On the edge of evolution. In R. Owen (Ed.",
        "La Salle, IL: Open Court Publishing. Dreyfus, H. L., & Kelly, S. D. (2007).",
        "Enjoying the spread: Conscious externalism reconsidered. Mind, 121(483), 731–751.",
        "Ecological Psychology, 27(3), 236–250. Golonka, S., & Wilson, A. D. (2016).",
        "The division of cognitive labor. Journal of Philosophy, 87, 5–22.",
        "Propositional attitudes and mental acts. Thought, 1, 239–245. Reichenbach, H. (1947).",
        "Psychological Review, 123, 324–347. Clark, H., & Carlson, T. (1982). Hearers and speech acts.",
        "Philosophical Review, 77(1), 90–95. Wiggins, D. (2001). Sameness and substance renewed.",
        "Mellor, D. H. (1995). The facts of causation. London: Routledge. Merricks, T. (1999).",
        "The metaphysics of groups. Philosophical Studies, 149(2), 251–267. Epstein, B.",
        "Baxter, D. L. M. (1988b). Identity in the loose and popular sense.",
        "New York: Cambridge. Kim, J. (1993b). Mental causation in a physical world.",
        "New York: Simon and Schuster. Searle, J. R. (2005). What is an institution?",
        "Sellars, W. (1953b). Inference and meaning. Mind, 62, 313–338. Sellars, W. (1953c).",
        "The British Journal for the Philosophy of Science, 62(4), 857–894. Carroll, L. (1994).",
        "(1989). Multicultural education. Needham Heights, MA: Allyn & Bacon.",
        "Philosophical Quarterly, 50, 305–319. Priest, G. (2006a). Doubt truth to be a liar.",
        "Cano, S. J. and J. C. Hobart 2011. The problem with health measurement.",
    ],
}

DATA = {
    1: [
        # found
        "No Grandfather, no Father; no Father, no Tim; no Tim, no killing.",
        "Snow falls and is white; the falling is a process, the whiteness is not.",     # ^ ^ - - ^; - ^ - - - ^ -; - ^ - - ^
        "We sometimes say: in later life I will be a different person.",
        "The game, one would like to say, has not only rules but also a point.",
        "Suppose that I cling to some rock as a mere means of escaping death.",
        "One of my strongest desires is that Venice never be destroyed.",
        "My mother did have many months of suffering, but she is now dead.",
        "One of my strongest desires was to be a successful parent.",
        "What does it mean to stop when the marks of going on are no longer?",
        "Suppose, as I stare at a glass in front of me, I say or think: There.",
        "Why is science so rare and faith so common in human history?",
        "We are not simply fallible at the margins but broadly inept.",                 # - - ^ ^ -; ^ - - - - ^ -; - ^ - - ^
        "How can man, who is born free, rightly come to be everywhere in chains?",
        "When I turn my eye inward, I find nothing but doubt and ignorance.",
        "You have an auto accident one winter night on a lonely road.",
        "What matters for now is not how we begin, but how we continue.",
        "Who can be loyal to a God who cannot be asked for anything?",
        "You may undersell a competitor, but you must not murder him.",
        "A proposition contains the form, but not the content, of its sense.",
        "Look at the blue of the sky and say to yourself How blue the sky is!",
        "I am not used to measuring temperatures on the Fahrenheit scale.",
        "Fear for others is only a shade better than fear for ourselves.",
        "Why was the world not created sooner? Because there was no sooner.",
        "How many facts or propositions are conveyed by a photograph?",
        "We often succumb to temptation with calm and even with finesse.",
        "Before we get out of the rabbit-hole, we need to fall into it.",

        # real haikus (not necessarily 5-7-5)
        "An old silent pond. A frog jumps into the pond — Splash! Silence again.",      # - ^ ^ - ^; - ^ ^ - - - ^; ^ ^ - - ^
        "A world of dew, And within every dewdrop A world of struggle.",                # - ^ - ^; - - ^ ^ - ^ -; - ^ - ^ -
        "The light of a candle Is transferred to another candle — Spring twilight",
        "Over the wintry Forest, winds howl in rage With no leaves to blow.",
        "The apparition of these faces in the crowd; Petals on a wet, black bough.",    # - - - ^ - - - ^ - - - ^; ^ - - - ^ ^ ^
        "The taste Of rain — Why kneel?",
        "love between us is speech and breath. loving you is a long river running.",
        "The west wind whispered, And touched the eyelids of spring: Her eyes, Primroses.",
        "Whitecaps on the bay: A broken signboard banging In the April wind.",
        "an aging willow — its image unsteady in the flowing stream",
        "Snow in my shoe Abandoned Sparrow's nest",
        "this piercing cold – in the bedroom, I have stepped on my dead wife's comb",
        "the Flower Festival – a mother’s womb is only for temporary lodging",
        "sound of dance music — the last fishing boat throbs into place",
        "shipping oars I hold my breath to hear snow on the water",
        "after the crash the doll’s eyes jammed open",
        "midday heat soldiers on both sides roll up their sleeves",
        "cold night the dashboard lights of another car",
        "dune wind — the blackened seed pods of a bush lupine",
        "On a branch floating downriver a cricket, singing.",
        "As cool as the pale wet leaves of lily-of-the-valley She lay beside me in the dawn.",
        "Lightning shatters the darkness ― the night heron's shriek.",
        "A freezing morning: I left a bit of my skin on the broomstick",
        "I write, erase, rewrite, Erase again, and then A poppy blooms",
        "fallen leaves the abbot sweeps around them",
        "losing its name a river enters the sea",
        "Moon's brightness I wonder where they're bombing",
        "First snow Falling On the half-finished bridge.",
        "See the river flow In a long unbroken line On the field of snow.",
        "Sudden spring storm-a family of ducks paddles around the deserted lake.",
        "The summer river: although there is a bridge, my horse goes through the water.",
        "Sick on a journey-Over parched fields Dreams wander on.",
    ],
    0: [

        # found
        "Further constraints could be added, but they will not be considered here.",    # ^ - - ^ - - ^ -; - - - ^ - - ^ - -
        "In this sense, at least, words like “ready” are clearly context-sensitive.",
        "Also, some special flexibility in the theory is discussed.",
        "Similarly, of course, for my stepping back from my preferences.",
        "After all, there is nothing indeterminate about such cases.",
        "Its premises claim the least, and are therefore the hardest to deny.",
        "The evidence gives little support to any of these suggestions.",
        "I will return to this matter when it becomes relevant later.",
        "What should worry us about the ideal objects is the following.",
        "In neither case is synonymy to be claimed for the paraphrase.",
        "In neither case does the sentence refer to a generic action.",
        "But there are plenty of other contexts in which the same need presses.",
        "But these events do not sound like ordinary bodily movements.",
        "We can, however, take it as given that most beliefs are correct.",
        "This reply does not, as might first be thought, merely restate the problem.",
        "But then there is a question how we understand the metalanguage.",
        "Our problem is that they have altogether too much in common.",
        "Even with working models there are limits to isomorphism.",
        "The last phrase, I have been suggesting, contains an ambiguity.",
        "Here too, I think it is clear that the evidence supports my account.",
        "Why are the authors of these theories not impressed by these examples?",
        "There are several such puzzling examples in the literature.",
        "Such costs would not be lightly recouped, one would think. These are good questions.",
        "The second concept which is in question is that of necessity.",
        "But even when they are unhappy, I do not think that they are bored.",
        "In his next chapter, he maintains the same thesis as regards number.",
        "In each there are two kinds, one immediate and one derivative.",
        "This seems to show that we must distinguish between content and object.",
        "More complicated propositions can be dealt with on the same lines.",
        "At best, such a claim is controversial, at worst, obviously false.",
        "Moreover, it is plausible that sometimes they ought to come apart.",
        "For some discussion of dispositions, see a few paragraphs hence.",
        "With this in mind, let us turn to the second stage of their argument.",
        "We present them here, and discuss some related conceptions of set.",
        "See the entry on the interpretation of probability.",
        "More recent studies have demonstrated that things are much more complex.",
        "Several problems with this program make themselves felt immediately.",
        "Therefore they are not eligible to stand in causal dependence.",
        "But if this is a case of piecemeal causation, we have no problem.",
        "These verbs take clauses rather than direct objects as their complements.",
        "Those assumptions are controversial, but I need not defend them here.",
        "The limits discussed in this chapter are far more prosaic than those.",
        "Endless examples can be constructed to the foregoing pattern.",
        "Examples of this type can be constructed for the other senses.",
        "Rather, it connects absolute and relative justification.",
        "Nevertheless, I want to proceed on a less adventurous track.",
        "Nevertheless, this is an important part of objectivity.",
        "Otherwise it is not freedom that I display but weakness of will.",
        "While this seems to me true, there is a natural way to dispute it.",
        "Rather it depends on the truth about ethics. What I think is this.",
        "Rational agents make things happen, that is, they are efficacious.",
        "The distribution of opportunities is also important.",
        "In addition to her studies, she devoted time to writing plays.",
        "Therefore, He knows the entirety of that which He has determined.",
        "He later became a member of the right wing Hegelian school.",
        "That traditional view dominated mainstream readings of the text.",
        "Eventually, he needed people like his wife to read to him.",
        "A molecular fact f is a conjunction of atomic facts.",
        "Is not one of these partitions privileged by the grounding relation?",
        "However, there is a deeper result here which we discuss below.",
        "Thus, the class of all cardinals is not a set, but a proper class.",
        "Matthew Clayton and Richard Arneson press this complaint against Rawls.",
        "The analogy with grammar might seem to break down at just this point.",
        "To understand this distinction, consider the following cases.",
        "There are many ways in which one can attempt to block the argument.", 
        "The real issue, to reiterate the point, is one of relevance.",
        "The above list is not meant to be exhaustive or especially clean.",
        "Interested readers may listen to two sound clips of Russell speaking.",
        "A fourth volume on geometry was planned but never completed.",
        "APPENDIX B Some More Questions About Science [For context, see p.",
        "Consequently, the above so-called law is not a law of nature.",
        "From this primitive conjunction follow many important results.",
        "To do this, we need a bridge between the abstract and concrete domains.",
    ],
}

TEST_SOURCES = {
    1: [
    ],
    0: [
    ],
}

def get(source=DATA):
    data = []
    target = []
    t1 = time.time()
    for cls, texts in IS_TEXT.iteritems():
        for text in texts:
            data.append(text)
            target.append(cls)
    return data, target
